name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # Runs every day at midnight UTC
  workflow_dispatch:

jobs:
  snake:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: piyushshrma
          outputs: dist/snake.svg
      - uses: actions/upload-artifact@v3
        with:
          name: snake
          path: dist/snake.svg
      - name: Commit and push if changed
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git checkout main
          mv dist/snake.svg ./
          git add snake.svg
          git commit -m "Updated snake contribution graph" || exit 0
          git push
